import img0 from "./coffee_dark.jpg";
import img1 from "./coffee_light.jpg";
import img2 from "./tea_1.jpg";
import img3 from "./tea_2.jpg";
import img4 from "./chocolate.jpg";
import img5 from "./merch.jpg";
import img6 from "/Users/thejourneyville/Documents/vscode/react/koana_v2/src/layout/NavMenu/koana_logo copy.png";

// export const imagesData = [
//     {
//         id: 0,
//         cat: "coffee",
//         image: img6,
//         name: "product name",
//         price: 69420,
//         weight: "#",
//         unit: "weight",
//         desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae quae neque dicta nulla voluptatum vel dolorum numquam ducimus qui, odio tenetur magni libero odit at deleniti provident? Temporibus blanditiis, incidunt ea eum voluptatibus facilis iure aperiam in quisquam impedit accusantium illum earum dolore qui nesciunt, deserunt deleniti culpa optio nisi.",
//         inventory: 5,
//     },
//     {
//         id: 1,
//         cat: "coffee",
//         image: img6,
//         name: "product name",
//         price: 69420,
//         weight: "#",
//         unit: "weight",
//         desc: "product description",
//         inventory: 5,
//     },
//     {
//         id: 2,
//         cat: "coffee",
//         image: img6,
//         name: "product name",
//         price: 69420,
//         weight: "#",
//         unit: "weight",
//         desc: "product description",
//         inventory: 5,
//     },
//     {
//         id: 3,
//         cat: "coffee",
//         image: img6,
//         name: "product name",
//         price: 69420,
//         weight: "#",
//         unit: "weight",
//         desc: "product description",
//         inventory: 5,
//     },
//     {
//         id: 4,
//         cat: "coffee",
//         image: img6,
//         name: "product name",
//         price: 69420,
//         weight: "#",
//         unit: "weight",
//         desc: "product description",
//         inventory: 5,
//     },
//     {
//         id: 5,
//         cat: "coffee",
//         image: img6,
//         name: "product name",
//         price: 69420,
//         weight: "#",
//         unit: "weight",
//         desc: "product description",
//         inventory: 5,
//     },

// ];

export const imagesData = [
    {
        id: 0,
        cat: "coffee",
        image: img0,
        name: "Koana Speciality Med-Dark Roast",
        price: 30,
        weight: 7,
        unit: "oz",
        desc: "Koana House Roasted Med-Dark Ka'u coffee",
        inventory: 0,
    },
    {
        id: 1,
        cat: "coffee",
        image: img1,
        name: "Koana Speciality Med-Light Roast",
        price: 30,
        weight: 7,
        unit: "oz",
        desc: "Koana House Roasted Med-Light Ka'u coffee",
        inventory: 5,
    },
    {
        id: 2,
        cat: "tea",
        image: img2,
        name: "Koana's Volcano Green Tea",
        price: 19,
        weight: 20,
        unit: "g",
        desc: "Light gentle Volcano Green Tea from Second Alarm Farm",
        inventory: 5,
    },
    {
        id: 3,
        cat: "tea",
        image: img3,
        name: "Koana's Volcano Earl Grey Tea",
        price: 19,
        weight: 20,
        unit: "g",
        desc: "Refreshing Volcano Earl Grey Tea from Second Alarm Farm",
        inventory: 5,
    },
    {
        id: 4,
        cat: "food",
        image: img4,
        name: "Chocolate Lava Mix",
        price: 18,
        weight: 150,
        unit: "g",
        desc: "Koana's own special belnd of spicy chocolate mix, vegan-friendly",
        inventory: 5,
    },
    {
        id: 5,
        cat: "merch",
        image: img5,
        name: "Koana's Coffee Flower",
        price: 16,
        weight: undefined,
        unit: undefined,
        desc: "Pin exclusively designed for Koana, exactly size of a coffee flower blossom, so you can share your love for coffee and nature wherever you go.",
        inventory: 5,
    },
];
